public enum CursorType {
    None,
    Default = 1,
    DownArrow = 2,
    GreenCrosshair = 3,
    InvalidCommand = 4,
    LeftArrow = 5,
    LowerLeftArrow = 6,
    LowerRightArrow = 7,
    MagnifyingGlass = 8,
    RedCrosshair = 9,
    RightArrow = 10,
    SmallGreenCrosshair = 16,
    UpArrow = 11,
    UpperLeftArrow = 12,
    UpperRightArrow = 13,
    Watch = 14,
    YellowCrosshair = 15,
    LeftMouseDown = 16
}
